install.packages("sqldf")
library(sqldf)
closeAllConnections()
household <- read.csv.sql('household_power_consumption.txt', sql = "select * from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep =";")
hist(household$Global_active_power, col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
